### ISSUE TITLE
Why DiffMOT is the first to introduce a diffusion probabilistic model into the MOT?

### ISSUE THREAD

**Issue by RainBowLuoCS** [Kroery/DiffMOT#1]
If DiffMOT is the first to introduce a diffusion probabilistic model into the MOT to tackle non-linear motion prediction, then what is DiffusionTrack, to be precise, DiffMOT is the first approach to promote diffuion-based tracker to SOTA, right?

**Comment by RainBowLuoCS** [comment]
Great！ DiffMOT is a wonderful work. Why not explain distinctions between DiffMOT and DiffusionTrack clearly in the releated work, it is easy to misunderstand.

**Comment by RainBowLuoCS** [comment]
Great！ DiffMOT is a wonderful work. Why not explain distinctions between DiffMOT and DiffusionTrack clearly in the releated work, it is easy to misunderstand.

**Comment by Kroery** [comment]
That's a good idea. We will consider adopting your suggestion in the future updated paper.
