### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by cedricnam** [Kroery/DiffMOT#15]
Where can i get det_dir, info_dir, reid_dir? Thanks

![Screenshot from 2024-05-14 11-57-22](https://github.com/Kroery/DiffMOT/assets/101238328/77a0a936-490b-48b6-a772-a2f60a2759e8)

**Comment by budabird** [comment]
i have the same question as a beginner！

**Comment by budabird** [comment]
> @budabird @cedricnam you can use the detection results and embeddings that they have provided. there are links to download them in the ReadMe: Tracking section. afterwards just modify the path to where you've saved them.

thanks for your help! i have confirmed the det_dir and reid_dir,but where can i get the info_dir?

**Comment by ranakhonsari** [comment]
> > @budabird @cedricnam you can use the detection results and embeddings that they have provided. there are links to download them in the ReadMe: Tracking section. afterwards just modify the path to where you've saved them.
> 
> thanks for your help! i have confirmed the det_dir and reid_dir,but where can i get the info_dir?

that is the path to the val folder in the dataset.

**Comment by cedricnam** [comment]
thanks everyone, i undertand, i will close this issue
